default_language_version:
    python: python3
repos:
-   repo: https://github.com/geritwagner/pipeline-validation-hooks
    rev: d4706982ee39f9a6d8660bdf4aeeb6f14fa0683b
    hooks:
    -   id: check
        name: Check consistency of data
        entry: pipeline_validation_hooks/check.py
        language: script
        files: 'references.bib|paper.md'
    -   id: format
        name: Format references
        entry: pipeline_validation_hooks/format.py
        language: script
        files: 'references.bib|paper.md'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
