default_language_version:
    python: python3
repos:
-   repo: https://github.com/geritwagner/pipeline-validation-hooks
    rev: d0e509fc0fec01167afafe252ef756fef86d7678
    hooks:
    -   id: check
        name: "ReviewManager: checks"
        entry: pipeline_validation_hooks/check.py
        language: script
        files: 'references.bib|paper.md'
    -   id: format
        name: "ReviewManager: format"
        entry: pipeline_validation_hooks/format.py
        language: script
        files: 'references.bib|paper.md'
    -   id: report
        name: "ReviewManager: report"
        entry: pipeline_validation_hooks/report.py
        language: script
        stages: [prepare-commit-msg]
    -   id: sharing
        name: "ReviewManager: sharing"
        entry: pipeline_validation_hooks/sharing.py
        language: script
        stages: [push]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
