[project]
name = "colrev.meta-analysis"
description = "CoLRev package for meta-analysis"
version = "0.1.0"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
review_type = "colrev.packages.meta-analysis.meta-analysis:MetaAnalysis"
