version: 2

# Build PDF & ePub
# formats:
#  - epub
#  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - pip install .[docs]

sphinx:
  configuration: docs/source/conf.py
