[tool.poetry]
name = "colrev"
version = "0.6.0" # automatically injected by poetry-dynamic-versioning
description = "Core engine for CoLRev (colaborative literature reviews)"
authors = ["Gerit Wagner <gerit.wagner@hec.ca>", "Julian Prester <julian.prester@sydney.edu.au>"]
license = "MIT"
readme = "README.md"
homepage="https://github.com/geritwagner/colrev"
repository = "https://github.com/geritwagner/colrev"
documentation = "https://github.com/geritwagner/colrev"
keywords = ["research", "reproducible research", "open science", "literature", "literature review", "systematic review", "systematic literature review"]
classifiers = [
   "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
include = ["CONTRIBUTING.md", "CHANGELOG.md", "LICENSE", "README.md", "colrev/py.typed"]

[tool.poetry.scripts]
colrev = "colrev.ui_cli.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
alphabet-detector = "^0.0.7"
ansiwrap = "^0.8.4"
beautifulsoup4 = "^4.11.1"
click8 = "^8.0.1"
click_completion = "^0.5.2"
crossrefapi = "^1.5.0"
cx-Freeze = "^6.11.1"
dacite = "^1.6.0"
daff = "^1.3.46"
dedupe = "^2.0.19"
dictdiffer = "^0.9.0"
docker = "6.0.0"
GitPython= "^3.1.29"
lingua-language-detector = "^1.1.3"
lxml = "^4.9.1"
nameparser = "^1.1.1"
opensearch-py = "^2.0.0"
pandas = "^1.5.0"
pandasql = "^0.7.3"
"pdfminer.six" = "^20220524"
psutil = "^5.9.2"
pybtex = "^0.24.0"
PyPDF2 = "^1.28.6"
"python-Levenshtein" = "^0.12.2"
PyYAML = "^6.0.0"
p-tqdm = "^1.4.0"
requests = "^2.28.1"
requests-cache = "^0.9.6"
thefuzz = "^0.19.0"
tqdm = "^4.64.1"
transitions = "^0.8.11"
timeout-decorator = "^0.5.0"
"zope.interface" = "^5.5.0"
pycountry = "^22.3.5"
glom = "^22.1.0"
pre-commit = "^2.20.0"
Jinja2 = "^3.1.2"
dataclasses-jsonschema = "^2.15.3"
Flask = "^2.2.2"
Flask-Cors = "^3.0.10"

[tool.poetry.dev-dependencies]
coverage = "^6.5.0"
pytest = "^7.1.3"
Sphinx = "^5.2.3"
sphinx-autodoc-typehints = "^1.19.4"
sphinx-click = "^4.3.0"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-bibtex = "^2.5.0"
tox = "^3.26.0"
types-click = "^7.1.8"

[build-system]
requires = ["poetry>=1.2.0b1"]
build-backend = "poetry.core.masonry.api"
