[project]
name = "colrev.curation_dedupe"
description = "CoLRev package for curation_dedupe"
version = "0.1.0"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
dedupe = "colrev.packages.curation_dedupe.curation_dedupe:CurationDedupe"
