[project]
name = "colrev.citeas"
description = "CoLRev package for citeas"
version = "0.1.0"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
prep = "colrev.packages.citeas.citeas:CiteAsPrep"
