[project]
name = "colrev.year_vol_iss_prep"
description = "CoLRev package for year_vol_iss_prep"
version = "0.1.0"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
prep = "colrev.packages.year_vol_iss_prep.year_vol_iss_prep:YearVolIssPrep"
