[project]
name = "colrev.ieee"
description = "CoLRev package for ieee"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" },
    { name = "Rhea Nguyen"},
    { name = "Malou Schmidt"},
    { name = "Frederic Fischer"},
    { name = "Janus Fiegen"},
    { name = "Albert Borchardt"}
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "experimental"
search_source = "colrev.packages.ieee.src.ieee:IEEEXploreSearchSource"
