default_language_version:
    python: python3
repos:
-   repo: https://github.com/geritwagner/colrev-hooks
    rev: 22fce71d34747b2aa6c323c842382a4364938bb9
    hooks:
    -   id: colrev-hooks-format
        name: "CoLRev ReviewManager: format"
        entry: colrev-hooks-format
        language: python
        pass_filenames: false
    -   id: colrev-hooks-check
        name: "CoLRev ReviewManager: check"
        entry: colrev-hooks-check
        language: python
        pass_filenames: false
    -   id: colrev-hooks-report
        name: "CoLRev ReviewManager: report"
        entry: colrev-hooks-report
        language: python
        stages: [prepare-commit-msg]
        pass_filenames: false
    -   id: colrev-hooks-share
        name: "CoLRev ReviewManager: share"
        entry: colrev-hooks-share
        language: python
        stages: [push]
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
