[project]
name = "colrev.pdf_get_man_cli"
description = "CoLRev package for pdf_get_man_cli"
version = "0.1.0"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
pdf_get_man = "colrev.packages.pdf_get_man_cli.pdf_get_man_cli:CoLRevCLIPDFGetMan"
