[project]
name = "colrev.pubmed"
description = "CoLRev package for pubmed"
version = "0.1.0"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
search_source = "colrev.packages.pubmed.pubmed:PubMedSearchSource"
prep = "colrev.packages.pubmed.pubmed_metadata_prep:PubmedMetadataPrep"
