default_language_version:
    python: python3
repos:
-   repo: https://github.com/geritwagner/colrev-hooks
    rev: d0e509fc0fec01167afafe252ef756fef86d7678
    hooks:
    -   id: format
        name: "ReviewManager: format"
        entry: colrev_hooks/format.py
        language: script
        files: 'references.bib|paper.md'
    -   id: check
        name: "ReviewManager: checks"
        entry: colrev_hooks/check.py
        language: script
        files: 'references.bib|paper.md'
    -   id: report
        name: "ReviewManager: report"
        entry: colrev_hooks/report.py
        language: script
        stages: [prepare-commit-msg]
    -   id: sharing
        name: "ReviewManager: sharing"
        entry: colrev_hooks/sharing.py
        language: script
        stages: [push]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 5276c7093b9e29c0594d173c4d253c2380f1e51d
    hooks:
    - id: markdownlint-fix
