version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    volumes:
      # Using just a bind mount for simplicity, but could use a proper Docker volume later
      - ./index:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      # HTTPS turned off for simplicity since this is only running locally for now
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9300:9300"
      - "9200:9200"
