[project]
name = "colrev.add_journal_ranking"
description = "CoLRev package for add_journal_ranking"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" },
    { name = "Alexa Steinheimer"},
    { name = "Robert Ahr"},
    { name = "Thomas Fleischmann"},
    { name = "Anton Liam Frisch"}
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "experimental"
prep = "colrev.packages.add_journal_ranking.src.add_journal_ranking:AddJournalRanking"
