[project]
name = "colrev.ui_web"
description = "Web-UI package for CoLRev"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" },
    { name = "Jessica Petry Klarmann"},
    { name = "Katharina Maria Ernst"},
    { name = "Luca Rita Ossendorf"},
    { name = "Simon Mühlbauer"}
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
