[project]
name = "colrev.unpaywall"
description = "CoLRev package for unpaywall"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
pdf_get = "colrev.packages.unpaywall.src.unpaywall:Unpaywall"
search_source = "colrev.packages.unpaywall.src.unpaywall_search_source:UnpaywallSearchSource"
