[project]
name = "colrev.github_pages"
description = "CoLRev package for github_pages"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Julian Prester", email = "julian.prester@sydney.edu.au" },
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "maturing"
data = "colrev.packages.github_pages.src.github_pages:GithubPages"
