name: Tests

# Run tests whenever the build passes
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test-minimal-deps:
    name: test-minimal-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install pytest
        pip install --no-cache-dir .
    - name: Run minimal-deps tests
      run: |
        pytest tests/minimal/

  test-full-deps:
    needs: test-minimal-deps
    name: test-full-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install pytest
        pip install pytest-mock
        pip install --no-cache-dir .
    - name: Run full-deps tests
      run: |
        pytest tests/full/
